### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by sverhoeven** [fair-workflows/NanopubJL#1]
I tried to run the extension with `docker-compose up`, but got the following error

```shell
Step 10/11 : RUN jupyter-serverextension enable --py NanopubJL &&     jlpm && jlpm build && jupyter-labextension link . && jlpm build && jupyter-lab build
 ---> Running in 92032b51779d
Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-serverextension", line 11, in <module>
    sys.exit(main())
  ...
  File "/opt/conda/lib/python3.7/site-packages/fairworkflows/__init__.py", line 5, in <module>
    from .ro_crate import ROCrate
  File "/opt/conda/lib/python3.7/site-packages/fairworkflows/ro_crate.py", line 7, in <module>
    from . import cwl
  File "/opt/conda/lib/python3.7/site-packages/fairworkflows/cwl.py", line 6, in <module>
    from toil.cwl import cwltoil
  File "/opt/conda/lib/python3.7/site-packages/toil/cwl/cwltoil.py", line 78, in <module>
    from cwltool.utils import aslist, convert_pathsep_to_unix, get_listing, normalizeFilesDirs, CWLObjectType
ImportError: cannot import name 'get_listing' from 'cwltool.utils' (/opt/conda/lib/python3.7/site-packages/cwltool/utils.py)
ERROR: Service 'jupyterlab' failed to build: The command '/bin/sh -c jupyter-serverextension enable --py NanopubJL &&     jlpm && jlpm build && jupyter-labextension link . && jlpm build && jupyter-lab build' returned a non-zero code: 1
```

**Comment by raar1** [comment]
Hi @sverhoeven , thanks for letting me know. Seems there was a version update in one of the dependencies that broke things. I've removed that code as it was no longer necessary, and the docker image now seems to build properly again. Please try again and let me know if there's still a problem.

(Note that for me I needed to do ```docker-compose build --no-cache``` to actually force it to fetch the new version of the lib, so try that if you're still getting the same error)

**Comment by sverhoeven** [comment]
Thanks, the build works and nanopub extension appears in Jupyter Lab environment. Sadly searching for examples terms like `Homo Sapiens` or terms from http://nanopub.org/wordpress/?page_id=8 fail with

```
upyterlab_1       | [E 10:13:10.159 LabApp] Uncaught exception GET /NanopubJL/nanosearch?type_of_search=text&search_str=Picoides+villosus&1598263990007 (172.18.0.1)
jupyterlab_1       |     HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/NanopubJL/nanosearch?type_of_search=text&search_str=Picoides+villosus&1598263990007', version='HTTP/1.1', remote_ip='172.18.0.1')
jupyterlab_1       |     Traceback (most recent call last):
jupyterlab_1       |       File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
jupyterlab_1       |         result = method(*self.path_args, **self.path_kwargs)
jupyterlab_1       |       File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 3174, in wrapper
jupyterlab_1       |         return method(self, *args, **kwargs)
jupyterlab_1       |       File "/app/NanopubJL/search.py", line 22, in get
jupyterlab_1       |         results = fairworkflows.Nanopub.search_text(search_str)
jupyterlab_1       |       File "/opt/conda/lib/python3.7/site-packages/fairworkflows/nanopub.py", line 114, in search_text
jupyterlab_1       |         return Nanopub._search(searchparams=searchparams, max_num_results=max_num_results, apiurl=apiurl)
jupyterlab_1       |       File "/opt/conda/lib/python3.7/site-packages/fairworkflows/nanopub.py", line 180, in _search
jupyterlab_1       |         xmltree = et.ElementTree(et.fromstring(r.text))
jupyterlab_1       |       File "/opt/conda/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
jupyterlab_1       |         parser.feed(text)
jupyterlab_1       |       File "<string>", line None
jupyterlab_1       |     xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
jupyterlab_1       | [W 10:13:10.162 LabApp] Unhandled error
```

**Comment by raar1** [comment]
Hmm, ok I need to look into this and I'll get back to you. It seems that the first couple of links (all pointing to nextprot.org) are actually broken, so that might have something to do with it. For now if you try typing e.g. 'fair' and click on some results, that should work (and show you what the behaviour is normally like). But I'm going to investigate the strange errors you're getting now.

**Comment by sverhoeven** [comment]
Great, `fair` search term works. Seems multi word search terms throw an error.

**Comment by raar1** [comment]
Yep, I've looked into it and it's actually a problem with the grlc query itself where whitespace is upsetting virtuoso. I'll need to contact the person who maintains the nanopub repo to see about fixing that. Thanks for spotting this, I think we've somehow only been searching for single word terms up till now.

**Comment by raar1** [comment]
I've opened an issue for this ( [https://github.com/peta-pico/nanopub-api/issues/2](https://github.com/peta-pico/nanopub-api/issues/2) )
